version: 0.2

env:
  variables:
    ECR_REPO_URI: "<YOUR_ECR_REPO_URI>"  # Replace this
    IMAGE_TAG: "latest"
    EC2_USER: "ec2-user"
    EC2_HOST: "3.110.191.221"
    SSH_KEY_SECRET_NAME: "ASJ"  # You handle this in CodeBuild env or Secrets Manager

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing prerequisites...
      - yum update -y
      - yum install -y aws-cli unzip openssh

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO_URI
      - IMAGE_URI=$ECR_REPO_URI:$IMAGE_TAG
      - echo Image URI: $IMAGE_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .
      - echo Pushing image to ECR...
      - docker push $IMAGE_URI

  post_build:
    commands:
      - echo Deploying to EC2 instance...
      - echo "$EC2_SSH_PRIVATE_KEY" > key.pem
      - chmod 400 key.pem
      - |
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
          echo Updating EC2 environment...
          sudo yum install -y docker || true
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo docker rm -f nodeapp || true
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO_URI
          sudo docker pull $ECR_REPO_URI:$IMAGE_TAG
          sudo docker run -d --name nodeapp -p 80:3000 $ECR_REPO_URI:$IMAGE_TAG
        EOF
