version: 0.2

env:
  variables:
    ECR_REPO_URI: "845091770108.dkr.ecr.ap-south-1.amazonaws.com/cicd-new-repo"  # Replace this
    IMAGE_TAG: "latest"
    EC2_USER: "ec2-user"
    EC2_HOST: "3.110.191.221"
    SSH_KEY_SECRET_NAME: "ASJ"  # You handle this in CodeBuild env or Secrets Manager

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing prerequisites...
      - yum update -y
      - yum install -y aws-cli unzip openssh

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO_URI
      - IMAGE_URI=$ECR_REPO_URI:$IMAGE_TAG
      - echo Image URI: $IMAGE_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .
      - echo Pushing image to ECR...
      - docker push $IMAGE_URI

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG

      - echo "Preparing EC2 deployment..."
      - echo "$EC2_SSH_PRIVATE_KEY" > key.pem
      - chmod 400 key.pem

      - EC2_HOST=3.110.191.221
      - EC2_USER=ec2-user

      - echo "Connecting to EC2 instance and deploying app..."
      - >
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "
        sudo yum install -y docker || true &&
        sudo systemctl start docker &&
        sudo systemctl enable docker &&
        sudo docker rm -f nodeapp || true &&
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO_URI &&
        sudo docker pull $ECR_REPO_URI:$IMAGE_TAG &&
        sudo docker run -d --name nodeapp -p 80:3000 $ECR_REPO_URI:$IMAGE_TAG
        "

